//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronPigeon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronPigeon.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature on the address book entry is invalid..
        /// </summary>
        internal static string AddressBookEntrySignatureDoesNotMatch {
            get {
                return ResourceManager.GetString("AddressBookEntrySignatureDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decode base64 string..
        /// </summary>
        internal static string Base64DecodingFailure {
            get {
                return ResourceManager.GetString("Base64DecodingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of ICryptoServices must be supplied first..
        /// </summary>
        internal static string CryptoServicesRequired {
            get {
                return ResourceManager.GetString("CryptoServicesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect length..
        /// </summary>
        internal static string IncorrectLength {
            get {
                return ResourceManager.GetString("IncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when reading incoming message..
        /// </summary>
        internal static string InvalidMessage {
            get {
                return ResourceManager.GetString("InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message notification not intended for this recipient..
        /// </summary>
        internal static string MisdirectedMessage {
            get {
                return ResourceManager.GetString("MisdirectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This payload reference is missing a decryption key..
        /// </summary>
        internal static string PayloadDecryptionKeyMissing {
            get {
                return ResourceManager.GetString("PayloadDecryptionKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key data is not allowed..
        /// </summary>
        internal static string PrivateKeyDataNotAllowed {
            get {
                return ResourceManager.GetString("PrivateKeyDataNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key data is required..
        /// </summary>
        internal static string PrivateKeyDataRequired {
            get {
                return ResourceManager.GetString("PrivateKeyDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} must be set first..
        /// </summary>
        internal static string PropertyMustBeSetFirst {
            get {
                return ResourceManager.GetString("PropertyMustBeSetFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream must be readable..
        /// </summary>
        internal static string ReadableStreamRequired {
            get {
                return ResourceManager.GetString("ReadableStreamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time must be given in UTC..
        /// </summary>
        internal static string UTCTimeRequired {
            get {
                return ResourceManager.GetString("UTCTimeRequired", resourceCulture);
            }
        }
    }
}
