steps:
  - task: DockerInstaller@0
    displayName: Install docker CLI
    inputs:
      dockerVersion: 17.09.0-ce
  - task: Docker@2
    displayName: docker build
    inputs:
      command: build
      containerRegistry: $(acr)
      repository: ironpigeonwebsvc
      Dockerfile: src/IronPigeon.Relay/Dockerfile
      buildContext: $(Build.SourcesDirectory)
      tags: |
        latest
        $(Build.BuildNumber)
  - task: Docker@2
    displayName: docker push
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: push
      containerRegistry: $(acr)
      repository: ironpigeonwebsvc
      Dockerfile: src/IronPigeon.Relay/Dockerfile
      buildContext: $(Build.SourcesDirectory)
      tags: |
        latest
        $(Build.BuildNumber)
