steps:
  - task: DockerInstaller@0
    displayName: Install docker CLI
    inputs:
      dockerVersion: 17.09.0-ce
  - powershell: echo "##vso[task.setvariable variable=semver2;]$(& (./azure-pipelines/Get-nbgv.ps1) get-version -v SemVer2)"
    displayName: Calculate docker tag
  - task: Docker@2
    displayName: docker build
    inputs:
      command: build
      containerRegistry: $(acr)
      repository: ironpigeonwebsvc
      Dockerfile: src/IronPigeon.Relay/Dockerfile
      buildContext: $(Build.SourcesDirectory)
      tags: |
        latest
        $(semver2)
  - task: Docker@2
    displayName: docker push
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: push
      containerRegistry: $(acr)
      repository: ironpigeonwebsvc
      Dockerfile: src/IronPigeon.Relay/Dockerfile
      buildContext: $(Build.SourcesDirectory)
      tags: |
        latest
        $(semver2)
